### ISSUE TITLE
Editor support

### ISSUE THREAD

**Issue by ShalokShalom** [arcadia-unity/ArcadiaGodot#13]
I just got informed, that your implementation can read API calls from Godot and provides this information in all IDEs, who support Clojure - or at least in Emacs.

Can you give further information on this?

I think this is worth mentioning in the Readme.

**Comment by selfsame** [comment]
Hi @ShalokShalom 

Not exactly sure what you're referring to, can you elaborate? We can interop with C# and the Godot API but that's nothing special.

**Comment by ShalokShalom** [comment]
But not every binding has Godot API support in external editors.

**Comment by Justin712** [comment]
Ah, I'll clarify. I was describing the fantastic nREPL and socket support using CIDER and Miracle with Emacs to ShalokShalom. That and having personally tested this language binding for Godot pretty extensively, I recommended that Clojure be put in the "Almost there" category for the language support page. I believe that your project works incredibly well and putting it in "up and coming" isn't giving it the recognition it deserves for how usable it is.

Also I believe that Shalok would have already thought the same, but someone who's unfamiliar with Clojure might not actually register what "ArcadiaGodot has an nRepl (port 3722), a socket repl (port 5571) and an UDP repl (port 11211). See Arcadia for editor setup options." actually means. The live-coding capabilities using Emacs are a pretty impressive feature and I can see why Shalok is saying that it might not be clear enough for newcomers since it's a major selling point.

Hope that clears things up, and fantastic work on the implementation so far!

**Comment by ShalokShalom** [comment]
I still think its not clear at all.

**Comment by selfsame** [comment]
Hi @ShalokShalom

It's similar to F#, Clojure is hosted on the CLR so it can call Godot's C# bindings.

**Comment by Justin712** [comment]
> Hi @ShalokShalom
> 
> It's similar to F#, Clojure is hosted on the CLR so it can call Godot's C# bindings.

I believe Shalok is actually referring to the readme for beginners, not that he needs any extra explanation. Again, this issue was opened because your implementation was ranked quite a bit lower than it should've been, that's all, and I believe he was looking for the usability to be advertised a little more since your Clojure implementation is kind of a big deal hahaha

The current 2 line note about the nREPL might come across as word soup to the average person just browsing the distribution, when it's actually very easy to set up a connection between Emacs and Godot and send over code in real-time.

Sorry if it seems kinda like nit-picking, but really both Shalok and I were just hoping to correct the problem of this implementation seeming far less usable than it actually is.

Thanks!

**Comment by selfsame** [comment]
ahh ok, will think about it next time I rework the readme. thanks!

**Comment by ShalokShalom** [comment]
For people who are looking for 'just a good language for Godot' and not being familiar with Clojure, it seems like there is no IDE support at all.

I wouldn't know if Justin hasn't told me in chat.

I guess Clojure in Godot could become one of the solid choices, to know that I can have Godot API support in basically all IDEs - as I understand this now - is not only something unique to Arcadia and Clojure, it is also something a lot of people looking for a language binding are looking for.

Currently, its not supported in the eyes of the user, while its actually very good supported.

"A feature that is undocumented, could not exist at all for many users"

**Comment by Justin712** [comment]
> "A feature that is undocumented, could not exist at all for many users"

Hahaha yes, compared to the other languages on the list, it's definitely very underrated. The difference between picking Clojure up for Godot is like night and day, but only if you already know how Emacs Clojure live-coding works. I think the average person would find it to be practically magic.

In any case, I think we're all on the same page here! Keep up the great work, and I look forward to seeing more from you as well as implementation of that MAGIC compiler whenever that comes up!
