### ISSUE TITLE
[Suggestion] Automatic function hooks management

### ISSUE THREAD

**Issue by kwrooijen** [arcadia-unity/ArcadiaGodot#23]
One thing that feels a bit hacky / stiff is that you need to manually add the `ArcadiaHooks.cs` script to each scene that you want to script. It's also not apparent which Clojure files belong to which Scene(s). Instead maybe we could define hook functions within the clojure file and attach then to specific Scenes (possibly through metadata).

Something in the lines of:

```clojure
(ns game.player)

(defn ^{:hook/ready ["Scenes/Player"]} ready [self _]
  (println "player ready")
```

In this example we attach the ready callback (`:hook/ready`) to `"Scenes/Player"` (`"res://Scenes/Player.tscn"`). Since this is a vector of strings we can add these hooks to multiple scenes.

Benefits of this approach is that you can see where a script is being used and you don't have to click around in the editor.

We'd need a few things:

- Parse all source files and find all namespace/functions with hook metadata. (separate CLI tool? Or part of the watcher maybe?) It would be nice to be able to use [Edamame](https://github.com/borkdude/edamame) for this, but it might be a bit of work to convert that to CLR.
- ~Write an `tscn` editor. There are a few out there but so far I've only seen Python and Go. We might want to implement something in Clojure.~ Godot provides some functionality to modify tscn programmatically.

**Comment by selfsame** [comment]
Left a few notes in the closed PRs but I'll say a bit more here because i know it's not fun having PRs rejected:

Arcadia and ArcadiaGodot both have a design compromise of not generating Classes (mainly due to clojure's `gen-class` not behaving in runtime) and so we miss out on some nice things (user classes with method overrides that you can drag onto nodes/gameobjects, and having class properties exposed in the editor inspectors).  In practice though, the Hook pattern gets you fully into the system and beyond that there is plenty of personal choice on how you orchestrate things.  The hook system is unlikely to change or get new features added.

Additionally I've been keeping the amount of code in ArcadiaGodot to a minimum (there's drastically less than Arcadia) so some really well written feature PRs may get rejected

**Comment by kwrooijen** [comment]
Fair enough. I'm interested in creating a "pluggable" dependency that implements this feature instead. The problem I have right now i that I'm not sure how I'd create this since I need to tap into the repl/launch and repl/loadpath functions, and eventually the compiler. If that can't work / won't get accepted, I'll have to resort to maintaining my own fork which would be a real pain.

Any ideas on this?

**Comment by selfsame** [comment]
I *think* you could just make a new class that inherits `ArcadiaHook`, something like:

```c#
public class MyHook : ArcadiaHook
  public override void _EnterTree(){
    base._EnterTree()
    // your stuff here
  }
}
```

**Comment by kwrooijen** [comment]
I don't see how I'd be able to manipulate the compiler / watcher with this though? Unless I completely override the `Boot.Initialize()` with my code.
