### ISSUE TITLE
on german locale vector3 are returned with decimal commas instead of points

### ISSUE THREAD

**Issue by kamisori** [arcadia-unity/ArcadiaGodot#9]
https://twitter.com/wafflekater/status/1324474804074852353
on master 4b25387ba0c9db20fe8d0e21ccab2165c1933e84

other locales are probably also affected by this. using nrepl on godot 3.2.3 stable mono win64

edit: reproduced on ubuntu

**Comment by selfsame** [comment]
Hi @kamisori, thank you for the report.  Looks like this is due to how Godot mono's variant types print as strings (you get the same output if you `GD.Print(new Vector3(1.2, 0, 0));` in a C# script with locale that uses `,` as a decimal separator. I'm closing as I believe this only a display issue, but you could try opening an issue with Godot or waiting for the 4.0 release?

Thanks again!

**Comment by kamisori** [comment]
whatevs

**Comment by kamisori** [comment]
yeah, sorry you're probably right actually

i was pretty tired when i wrote my earlier comment and most likely just skimmed over your comment and wasnt happy with what i read, my bad
